# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\bergw\.qgis\python\plugins\VoGisProfilTool\ui_vogisprofile.ui'
#
# Created: Mon Aug 06 15:57:40 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_VoGisProfile(object):
    def setupUi(self, VoGisProfile):
        VoGisProfile.setObjectName(_fromUtf8("VoGisProfile"))
        VoGisProfile.resize(411, 512)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VoGisProfile.sizePolicy().hasHeightForWidth())
        VoGisProfile.setSizePolicy(sizePolicy)
        VoGisProfile.setMinimumSize(QtCore.QSize(411, 512))
        VoGisProfile.setMaximumSize(QtCore.QSize(411, 512))
        self.IDC_grpProfile = QtGui.QGroupBox(VoGisProfile)
        self.IDC_grpProfile.setGeometry(QtCore.QRect(5, 155, 400, 221))
        self.IDC_grpProfile.setObjectName(_fromUtf8("IDC_grpProfile"))
        self.IDC_radioCoords = QtGui.QRadioButton(self.IDC_grpProfile)
        self.IDC_radioCoords.setGeometry(QtCore.QRect(15, 130, 231, 17))
        self.IDC_radioCoords.setObjectName(_fromUtf8("IDC_radioCoords"))
        self.IDC_radioDrawLine = QtGui.QRadioButton(self.IDC_grpProfile)
        self.IDC_radioDrawLine.setGeometry(QtCore.QRect(10, 30, 226, 17))
        self.IDC_radioDrawLine.setChecked(False)
        self.IDC_radioDrawLine.setObjectName(_fromUtf8("IDC_radioDrawLine"))
        self.IDC_radioLineLayer = QtGui.QRadioButton(self.IDC_grpProfile)
        self.IDC_radioLineLayer.setGeometry(QtCore.QRect(10, 65, 261, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IDC_radioLineLayer.sizePolicy().hasHeightForWidth())
        self.IDC_radioLineLayer.setSizePolicy(sizePolicy)
        self.IDC_radioLineLayer.setChecked(True)
        self.IDC_radioLineLayer.setObjectName(_fromUtf8("IDC_radioLineLayer"))
        self.IDC_tbFromX = QtGui.QLineEdit(self.IDC_grpProfile)
        self.IDC_tbFromX.setGeometry(QtCore.QRect(114, 166, 113, 20))
        self.IDC_tbFromX.setObjectName(_fromUtf8("IDC_tbFromX"))
        self.IDC_tbFromY = QtGui.QLineEdit(self.IDC_grpProfile)
        self.IDC_tbFromY.setGeometry(QtCore.QRect(230, 166, 113, 20))
        self.IDC_tbFromY.setObjectName(_fromUtf8("IDC_tbFromY"))
        self.IDC_tbToX = QtGui.QLineEdit(self.IDC_grpProfile)
        self.IDC_tbToX.setGeometry(QtCore.QRect(114, 190, 113, 20))
        self.IDC_tbToX.setObjectName(_fromUtf8("IDC_tbToX"))
        self.IDC_tbToY = QtGui.QLineEdit(self.IDC_grpProfile)
        self.IDC_tbToY.setGeometry(QtCore.QRect(230, 190, 113, 20))
        self.IDC_tbToY.setObjectName(_fromUtf8("IDC_tbToY"))
        self.label = QtGui.QLabel(self.IDC_grpProfile)
        self.label.setGeometry(QtCore.QRect(84, 166, 26, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.IDC_grpProfile)
        self.label_2.setGeometry(QtCore.QRect(84, 193, 26, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.IDC_cbLineLayer = QtGui.QComboBox(self.IDC_grpProfile)
        self.IDC_cbLineLayer.setGeometry(QtCore.QRect(25, 85, 146, 22))
        self.IDC_cbLineLayer.setObjectName(_fromUtf8("IDC_cbLineLayer"))
        self.IDC_chkSelFeatures = QtGui.QCheckBox(self.IDC_grpProfile)
        self.IDC_chkSelFeatures.setGeometry(QtCore.QRect(175, 85, 226, 17))
        self.IDC_chkSelFeatures.setObjectName(_fromUtf8("IDC_chkSelFeatures"))
        self.label_3 = QtGui.QLabel(self.IDC_grpProfile)
        self.label_3.setGeometry(QtCore.QRect(115, 151, 76, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.IDC_grpProfile)
        self.label_4.setGeometry(QtCore.QRect(230, 151, 66, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.IDC_bDrawLine = QtGui.QPushButton(self.IDC_grpProfile)
        self.IDC_bDrawLine.setGeometry(QtCore.QRect(190, 28, 201, 23))
        self.IDC_bDrawLine.setObjectName(_fromUtf8("IDC_bDrawLine"))
        self.IDC_grpVertices = QtGui.QGroupBox(VoGisProfile)
        self.IDC_grpVertices.setGeometry(QtCore.QRect(5, 385, 400, 96))
        self.IDC_grpVertices.setObjectName(_fromUtf8("IDC_grpVertices"))
        self.IDC_radioEquiDistance = QtGui.QRadioButton(self.IDC_grpVertices)
        self.IDC_radioEquiDistance.setGeometry(QtCore.QRect(15, 20, 196, 17))
        self.IDC_radioEquiDistance.setChecked(True)
        self.IDC_radioEquiDistance.setObjectName(_fromUtf8("IDC_radioEquiDistance"))
        self.IDC_radioVertexCount = QtGui.QRadioButton(self.IDC_grpVertices)
        self.IDC_radioVertexCount.setGeometry(QtCore.QRect(15, 42, 171, 17))
        self.IDC_radioVertexCount.setObjectName(_fromUtf8("IDC_radioVertexCount"))
        self.IDC_radioVertices = QtGui.QRadioButton(self.IDC_grpVertices)
        self.IDC_radioVertices.setGeometry(QtCore.QRect(15, 65, 276, 17))
        self.IDC_radioVertices.setChecked(False)
        self.IDC_radioVertices.setObjectName(_fromUtf8("IDC_radioVertices"))
        self.IDC_dblspinDistance = QtGui.QDoubleSpinBox(self.IDC_grpVertices)
        self.IDC_dblspinDistance.setGeometry(QtCore.QRect(215, 15, 62, 22))
        self.IDC_dblspinDistance.setDecimals(3)
        self.IDC_dblspinDistance.setMinimum(0.001)
        self.IDC_dblspinDistance.setMaximum(1000000.0)
        self.IDC_dblspinDistance.setProperty(_fromUtf8("value"), 10.0)
        self.IDC_dblspinDistance.setObjectName(_fromUtf8("IDC_dblspinDistance"))
        self.IDC_dblspinVertexCnt = QtGui.QDoubleSpinBox(self.IDC_grpVertices)
        self.IDC_dblspinVertexCnt.setGeometry(QtCore.QRect(215, 40, 62, 22))
        self.IDC_dblspinVertexCnt.setDecimals(0)
        self.IDC_dblspinVertexCnt.setMinimum(2.0)
        self.IDC_dblspinVertexCnt.setMaximum(1000000.0)
        self.IDC_dblspinVertexCnt.setProperty(_fromUtf8("value"), 100.0)
        self.IDC_dblspinVertexCnt.setObjectName(_fromUtf8("IDC_dblspinVertexCnt"))
        self.IDC_grpRaster = QtGui.QGroupBox(VoGisProfile)
        self.IDC_grpRaster.setGeometry(QtCore.QRect(5, 10, 400, 136))
        self.IDC_grpRaster.setObjectName(_fromUtf8("IDC_grpRaster"))
        self.IDC_lvwRaster = QtGui.QListWidget(self.IDC_grpRaster)
        self.IDC_lvwRaster.setGeometry(QtCore.QRect(15, 25, 366, 96))
        self.IDC_lvwRaster.setObjectName(_fromUtf8("IDC_lvwRaster"))
        self.IDC_bCreatePlot = QtGui.QPushButton(VoGisProfile)
        self.IDC_bCreatePlot.setGeometry(QtCore.QRect(144, 485, 146, 23))
        self.IDC_bCreatePlot.setObjectName(_fromUtf8("IDC_bCreatePlot"))
        self.IDC_bClose = QtGui.QPushButton(VoGisProfile)
        self.IDC_bClose.setGeometry(QtCore.QRect(309, 485, 96, 23))
        self.IDC_bClose.setObjectName(_fromUtf8("IDC_bClose"))

        self.retranslateUi(VoGisProfile)
        QtCore.QObject.connect(self.IDC_bCreatePlot, QtCore.SIGNAL(_fromUtf8("clicked()")), VoGisProfile.plotProfile)
        QtCore.QObject.connect(self.IDC_bClose, QtCore.SIGNAL(_fromUtf8("clicked()")), VoGisProfile.accept)
        QtCore.QObject.connect(self.IDC_bDrawLine, QtCore.SIGNAL(_fromUtf8("clicked()")), VoGisProfile.drawLine)
        QtCore.QObject.connect(self.IDC_dblspinDistance, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), VoGisProfile.valueChangedEquiDistance)
        QtCore.QObject.connect(self.IDC_dblspinVertexCnt, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), VoGisProfile.valueChangedVertexCount)
        QtCore.QMetaObject.connectSlotsByName(VoGisProfile)

    def retranslateUi(self, VoGisProfile):
        VoGisProfile.setWindowTitle(QtGui.QApplication.translate("VoGisProfile", "VoGIS-Profiltool", None, QtGui.QApplication.UnicodeUTF8))
        self.IDC_grpProfile.setTitle(QtGui.QApplication.translate("VoGisProfile", " Lage der Profillinie(n) festlegen ", None, QtGui.QApplication.UnicodeUTF8))
        self.IDC_radioCoords.setText(QtGui.QApplication.translate("VoGisProfile", "gerade Profillinie zwischen zwei Punkten ", None, QtGui.QApplication.UnicodeUTF8))
        self.IDC_radioDrawLine.setText(QtGui.QApplication.translate("VoGisProfile", "Profillinie am Bildschirm zeichnen", None, QtGui.QApplication.UnicodeUTF8))
        self.IDC_radioLineLayer.setText(QtGui.QApplication.translate("VoGisProfile", "Profillinie(n) aus Linienthema übernehmen ", None, QtGui.QApplication.UnicodeUTF8))
        self.IDC_tbFromX.setInputMask(QtGui.QApplication.translate("VoGisProfile", "#000000000.000000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.IDC_tbFromY.setInputMask(QtGui.QApplication.translate("VoGisProfile", "#000000000.000000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.IDC_tbToX.setInputMask(QtGui.QApplication.translate("VoGisProfile", "#000000000.000000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.IDC_tbToY.setInputMask(QtGui.QApplication.translate("VoGisProfile", "#000000000.000000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("VoGisProfile", "von:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("VoGisProfile", "nach:", None, QtGui.QApplication.UnicodeUTF8))
        self.IDC_chkSelFeatures.setText(QtGui.QApplication.translate("VoGisProfile", "nur selektierte Elemente verwenden", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("VoGisProfile", "Rechtswert", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("VoGisProfile", "Hochwert", None, QtGui.QApplication.UnicodeUTF8))
        self.IDC_bDrawLine.setText(QtGui.QApplication.translate("VoGisProfile", "Profillinie (neu) digitalisieren", None, QtGui.QApplication.UnicodeUTF8))
        self.IDC_grpVertices.setTitle(QtGui.QApplication.translate("VoGisProfile", " Stützstellen festlegen ", None, QtGui.QApplication.UnicodeUTF8))
        self.IDC_radioEquiDistance.setText(QtGui.QApplication.translate("VoGisProfile", "Abstand zwischen den Profilpunkten", None, QtGui.QApplication.UnicodeUTF8))
        self.IDC_radioVertexCount.setText(QtGui.QApplication.translate("VoGisProfile", "Anzahl Profilepunkte pro Profil", None, QtGui.QApplication.UnicodeUTF8))
        self.IDC_radioVertices.setText(QtGui.QApplication.translate("VoGisProfile", "Profilepunkte erstellen an Knoten und Stützstellen", None, QtGui.QApplication.UnicodeUTF8))
        self.IDC_grpRaster.setTitle(QtGui.QApplication.translate("VoGisProfile", " Rastermodell(e) auswählen ", None, QtGui.QApplication.UnicodeUTF8))
        self.IDC_bCreatePlot.setText(QtGui.QApplication.translate("VoGisProfile", "Profil(e) erstellen", None, QtGui.QApplication.UnicodeUTF8))
        self.IDC_bClose.setText(QtGui.QApplication.translate("VoGisProfile", "Schließen", None, QtGui.QApplication.UnicodeUTF8))

