# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_vogisprofiltoolplot.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VoGISProfilToolPlot(object):
    def setupUi(self, VoGISProfilToolPlot):
        VoGISProfilToolPlot.setObjectName("VoGISProfilToolPlot")
        VoGISProfilToolPlot.resize(850, 472)
        VoGISProfilToolPlot.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(VoGISProfilToolPlot)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.IDC_bClose = QtWidgets.QPushButton(VoGISProfilToolPlot)
        self.IDC_bClose.setObjectName("IDC_bClose")
        self.gridLayout.addWidget(self.IDC_bClose, 3, 9, 1, 1)
        self.IDC_bDxfLine = QtWidgets.QPushButton(VoGISProfilToolPlot)
        self.IDC_bDxfLine.setObjectName("IDC_bDxfLine")
        self.gridLayout.addWidget(self.IDC_bDxfLine, 3, 6, 1, 1)
        self.IDC_bDxfPnt = QtWidgets.QPushButton(VoGISProfilToolPlot)
        self.IDC_bDxfPnt.setObjectName("IDC_bDxfPnt")
        self.gridLayout.addWidget(self.IDC_bDxfPnt, 3, 4, 1, 1)
        self.IDC_bShpPnt = QtWidgets.QPushButton(VoGISProfilToolPlot)
        self.IDC_bShpPnt.setObjectName("IDC_bShpPnt")
        self.gridLayout.addWidget(self.IDC_bShpPnt, 3, 3, 1, 1)
        self.IDC_bShpLine = QtWidgets.QPushButton(VoGISProfilToolPlot)
        self.IDC_bShpLine.setObjectName("IDC_bShpLine")
        self.gridLayout.addWidget(self.IDC_bShpLine, 3, 5, 1, 1)
        self.IDC_bACadTxt = QtWidgets.QPushButton(VoGISProfilToolPlot)
        self.IDC_bACadTxt.setObjectName("IDC_bACadTxt")
        self.gridLayout.addWidget(self.IDC_bACadTxt, 3, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(VoGISProfilToolPlot)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.IDC_cbDecimalDelimiter = QtWidgets.QComboBox(VoGISProfilToolPlot)
        self.IDC_cbDecimalDelimiter.setObjectName("IDC_cbDecimalDelimiter")
        self.IDC_cbDecimalDelimiter.addItem("")
        self.IDC_cbDecimalDelimiter.addItem("")
        self.horizontalLayout.addWidget(self.IDC_cbDecimalDelimiter)
        self.label_2 = QtWidgets.QLabel(VoGISProfilToolPlot)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.IDC_cbDelimiter = QtWidgets.QComboBox(VoGISProfilToolPlot)
        self.IDC_cbDelimiter.setEditable(False)
        self.IDC_cbDelimiter.setObjectName("IDC_cbDelimiter")
        self.IDC_cbDelimiter.addItem("")
        self.IDC_cbDelimiter.addItem("")
        self.IDC_cbDelimiter.addItem("")
        self.IDC_cbDelimiter.addItem("")
        self.IDC_cbDelimiter.setItemText(3, "")
        self.horizontalLayout.addWidget(self.IDC_cbDelimiter)
        self.IDC_chkHekto = QtWidgets.QCheckBox(VoGISProfilToolPlot)
        self.IDC_chkHekto.setObjectName("IDC_chkHekto")
        self.horizontalLayout.addWidget(self.IDC_chkHekto)
        self.IDC_chkLineAttributes = QtWidgets.QCheckBox(VoGISProfilToolPlot)
        self.IDC_chkLineAttributes.setChecked(True)
        self.IDC_chkLineAttributes.setObjectName("IDC_chkLineAttributes")
        self.horizontalLayout.addWidget(self.IDC_chkLineAttributes)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 10)
        self.IDC_frPlot = QtWidgets.QFrame(VoGISProfilToolPlot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IDC_frPlot.sizePolicy().hasHeightForWidth())
        self.IDC_frPlot.setSizePolicy(sizePolicy)
        self.IDC_frPlot.setMinimumSize(QtCore.QSize(0, 350))
        self.IDC_frPlot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.IDC_frPlot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.IDC_frPlot.setObjectName("IDC_frPlot")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.IDC_frPlot)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout.addWidget(self.IDC_frPlot, 0, 0, 1, 10)
        self.IDC_frToolbar = QtWidgets.QFrame(VoGISProfilToolPlot)
        self.IDC_frToolbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.IDC_frToolbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.IDC_frToolbar.setObjectName("IDC_frToolbar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.IDC_frToolbar)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout.addWidget(self.IDC_frToolbar, 1, 0, 1, 10)
        self.IDC_bText = QtWidgets.QPushButton(VoGISProfilToolPlot)
        self.IDC_bText.setObjectName("IDC_bText")
        self.gridLayout.addWidget(self.IDC_bText, 3, 0, 1, 1)
        self.IDC_bExcel = QtWidgets.QPushButton(VoGISProfilToolPlot)
        self.IDC_bExcel.setObjectName("IDC_bExcel")
        self.gridLayout.addWidget(self.IDC_bExcel, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 8, 1, 1)
        self.btnAddLayout = QtWidgets.QPushButton(VoGISProfilToolPlot)
        self.btnAddLayout.setObjectName("btnAddLayout")
        self.gridLayout.addWidget(self.btnAddLayout, 3, 7, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 10, 0, 1, 1)

        self.retranslateUi(VoGISProfilToolPlot)
        self.IDC_bClose.clicked.connect(VoGISProfilToolPlot.reject)
        self.IDC_bText.clicked.connect(VoGISProfilToolPlot.exportTxt)
        self.IDC_bShpPnt.clicked.connect(VoGISProfilToolPlot.exportShpPnt)
        self.IDC_bShpLine.clicked.connect(VoGISProfilToolPlot.exportShpLine)
        self.IDC_bExcel.clicked.connect(VoGISProfilToolPlot.exportCsvXls)
        self.IDC_bACadTxt.clicked.connect(VoGISProfilToolPlot.exportAutoCadTxt)
        self.IDC_bDxfPnt.clicked.connect(VoGISProfilToolPlot.exportDxfPnt)
        self.IDC_bDxfLine.clicked.connect(VoGISProfilToolPlot.exportDxfLine)
        QtCore.QMetaObject.connectSlotsByName(VoGISProfilToolPlot)

    def retranslateUi(self, VoGISProfilToolPlot):
        _translate = QtCore.QCoreApplication.translate
        VoGISProfilToolPlot.setWindowTitle(_translate("VoGISProfilToolPlot", "VoGIS Profil Tool"))
        self.IDC_bClose.setText(_translate("VoGISProfilToolPlot", "Schließen"))
        self.IDC_bDxfLine.setText(_translate("VoGISProfilToolPlot", "DXF Linie"))
        self.IDC_bDxfPnt.setText(_translate("VoGISProfilToolPlot", "DXF Punkt"))
        self.IDC_bShpPnt.setText(_translate("VoGISProfilToolPlot", "Shp Punkt"))
        self.IDC_bShpLine.setText(_translate("VoGISProfilToolPlot", "Shp Linie"))
        self.IDC_bACadTxt.setText(_translate("VoGISProfilToolPlot", "Autocad Text"))
        self.label.setText(_translate("VoGISProfilToolPlot", "Dezimalzeichen (für Text, csv):"))
        self.IDC_cbDecimalDelimiter.setItemText(0, _translate("VoGISProfilToolPlot", ","))
        self.IDC_cbDecimalDelimiter.setItemText(1, _translate("VoGISProfilToolPlot", "."))
        self.label_2.setText(_translate("VoGISProfilToolPlot", "Spaltentrennzeichen (Text):"))
        self.IDC_cbDelimiter.setItemText(0, _translate("VoGISProfilToolPlot", "tab"))
        self.IDC_cbDelimiter.setItemText(1, _translate("VoGISProfilToolPlot", ";"))
        self.IDC_cbDelimiter.setItemText(2, _translate("VoGISProfilToolPlot", ","))
        self.IDC_chkHekto.setText(_translate("VoGISProfilToolPlot", "Hektometrie Attribute"))
        self.IDC_chkLineAttributes.setText(_translate("VoGISProfilToolPlot", "Linien Attribute"))
        self.IDC_bText.setText(_translate("VoGISProfilToolPlot", "Textdatei"))
        self.IDC_bExcel.setText(_translate("VoGISProfilToolPlot", "Excel / CSV"))
        self.btnAddLayout.setText(_translate("VoGISProfilToolPlot", "Zum Layout hinzufügen"))

