# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_vogisprofiltoolmain.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VoGISProfilToolMain(object):
    def setupUi(self, VoGISProfilToolMain):
        VoGISProfilToolMain.setObjectName("VoGISProfilToolMain")
        VoGISProfilToolMain.resize(619, 938)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VoGISProfilToolMain.sizePolicy().hasHeightForWidth())
        VoGISProfilToolMain.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(VoGISProfilToolMain)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(VoGISProfilToolMain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 597, 910))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.IDC_widRaster = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.IDC_widRaster.setEnabled(True)
        self.IDC_widRaster.setObjectName("IDC_widRaster")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.IDC_widRaster)
        self.gridLayout_2.setContentsMargins(-1, 2, -1, 2)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.IDC_grpRaster = QtWidgets.QGroupBox(self.IDC_widRaster)
        self.IDC_grpRaster.setObjectName("IDC_grpRaster")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.IDC_grpRaster)
        self.gridLayout_3.setContentsMargins(-1, 3, -1, 0)
        self.gridLayout_3.setVerticalSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.IDC_listRasters = QtWidgets.QListWidget(self.IDC_grpRaster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IDC_listRasters.sizePolicy().hasHeightForWidth())
        self.IDC_listRasters.setSizePolicy(sizePolicy)
        self.IDC_listRasters.setMinimumSize(QtCore.QSize(0, 100))
        self.IDC_listRasters.setObjectName("IDC_listRasters")
        self.gridLayout_3.addWidget(self.IDC_listRasters, 2, 0, 1, 1)
        self.IDC_bSelectVisibleRasters = QtWidgets.QPushButton(self.IDC_grpRaster)
        self.IDC_bSelectVisibleRasters.setObjectName("IDC_bSelectVisibleRasters")
        self.gridLayout_3.addWidget(self.IDC_bSelectVisibleRasters, 0, 0, 1, 1)
        self.IDC_bRefreshRasterList = QtWidgets.QPushButton(self.IDC_grpRaster)
        self.IDC_bRefreshRasterList.setObjectName("IDC_bRefreshRasterList")
        self.gridLayout_3.addWidget(self.IDC_bRefreshRasterList, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.IDC_grpRaster, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.IDC_widRaster)
        self.IDC_widProfilLinien = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.IDC_widProfilLinien.setObjectName("IDC_widProfilLinien")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.IDC_widProfilLinien)
        self.gridLayout_4.setContentsMargins(-1, 2, -1, 2)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.IDC_grpProfilLinien = QtWidgets.QGroupBox(self.IDC_widProfilLinien)
        self.IDC_grpProfilLinien.setObjectName("IDC_grpProfilLinien")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.IDC_grpProfilLinien)
        self.gridLayout_5.setContentsMargins(-1, 2, -1, 2)
        self.gridLayout_5.setVerticalSpacing(1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.IDC_bDrawLine = QtWidgets.QPushButton(self.IDC_grpProfilLinien)
        self.IDC_bDrawLine.setObjectName("IDC_bDrawLine")
        self.gridLayout_5.addWidget(self.IDC_bDrawLine, 4, 0, 1, 1)
        self.IDC_chkOnlySelectedFeatures = QtWidgets.QCheckBox(self.IDC_grpProfilLinien)
        self.IDC_chkOnlySelectedFeatures.setObjectName("IDC_chkOnlySelectedFeatures")
        self.gridLayout_5.addWidget(self.IDC_chkOnlySelectedFeatures, 8, 0, 1, 1)
        self.IDC_chkLinesExplode = QtWidgets.QCheckBox(self.IDC_grpProfilLinien)
        self.IDC_chkLinesExplode.setChecked(True)
        self.IDC_chkLinesExplode.setObjectName("IDC_chkLinesExplode")
        self.gridLayout_5.addWidget(self.IDC_chkLinesExplode, 1, 0, 1, 1)
        self.IDC_cbLineLayers = QtWidgets.QComboBox(self.IDC_grpProfilLinien)
        self.IDC_cbLineLayers.setObjectName("IDC_cbLineLayers")
        self.gridLayout_5.addWidget(self.IDC_cbLineLayers, 7, 0, 1, 1)
        self.IDC_rbShapeLine = QtWidgets.QRadioButton(self.IDC_grpProfilLinien)
        self.IDC_rbShapeLine.setChecked(True)
        self.IDC_rbShapeLine.setObjectName("IDC_rbShapeLine")
        self.gridLayout_5.addWidget(self.IDC_rbShapeLine, 6, 0, 1, 2)
        self.IDC_rbDigi = QtWidgets.QRadioButton(self.IDC_grpProfilLinien)
        self.IDC_rbDigi.setObjectName("IDC_rbDigi")
        self.gridLayout_5.addWidget(self.IDC_rbDigi, 3, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.IDC_grpProfilLinien)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_7.setVerticalSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.IDC_tbFromX = QtWidgets.QLineEdit(self.groupBox)
        self.IDC_tbFromX.setObjectName("IDC_tbFromX")
        self.gridLayout_7.addWidget(self.IDC_tbFromX, 1, 1, 1, 1)
        self.IDC_tbFromY = QtWidgets.QLineEdit(self.groupBox)
        self.IDC_tbFromY.setObjectName("IDC_tbFromY")
        self.gridLayout_7.addWidget(self.IDC_tbFromY, 1, 2, 1, 1)
        self.IDC_tbToX = QtWidgets.QLineEdit(self.groupBox)
        self.IDC_tbToX.setObjectName("IDC_tbToX")
        self.gridLayout_7.addWidget(self.IDC_tbToX, 2, 1, 1, 1)
        self.IDC_tbToY = QtWidgets.QLineEdit(self.groupBox)
        self.IDC_tbToY.setMaxLength(17)
        self.IDC_tbToY.setCursorPosition(0)
        self.IDC_tbToY.setObjectName("IDC_tbToY")
        self.gridLayout_7.addWidget(self.IDC_tbToY, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 10, 0, 1, 1)
        self.IDC_chkLinesMerge = QtWidgets.QCheckBox(self.IDC_grpProfilLinien)
        self.IDC_chkLinesMerge.setChecked(True)
        self.IDC_chkLinesMerge.setObjectName("IDC_chkLinesMerge")
        self.gridLayout_5.addWidget(self.IDC_chkLinesMerge, 2, 0, 1, 1)
        self.IDC_rbStraigthLine = QtWidgets.QRadioButton(self.IDC_grpProfilLinien)
        self.IDC_rbStraigthLine.setObjectName("IDC_rbStraigthLine")
        self.gridLayout_5.addWidget(self.IDC_rbStraigthLine, 9, 0, 1, 1)
        self.gridLayout_4.addWidget(self.IDC_grpProfilLinien, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.IDC_widProfilLinien)
        self.IDC_grpVertices = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IDC_grpVertices.sizePolicy().hasHeightForWidth())
        self.IDC_grpVertices.setSizePolicy(sizePolicy)
        self.IDC_grpVertices.setObjectName("IDC_grpVertices")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.IDC_grpVertices)
        self.gridLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_8.setVerticalSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.IDC_rbEquiDistance = QtWidgets.QRadioButton(self.IDC_grpVertices)
        self.IDC_rbEquiDistance.setChecked(True)
        self.IDC_rbEquiDistance.setObjectName("IDC_rbEquiDistance")
        self.gridLayout_8.addWidget(self.IDC_rbEquiDistance, 0, 0, 1, 1)
        self.IDC_dblspinDistance = QtWidgets.QDoubleSpinBox(self.IDC_grpVertices)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IDC_dblspinDistance.sizePolicy().hasHeightForWidth())
        self.IDC_dblspinDistance.setSizePolicy(sizePolicy)
        self.IDC_dblspinDistance.setDecimals(3)
        self.IDC_dblspinDistance.setMinimum(0.001)
        self.IDC_dblspinDistance.setMaximum(1000000.0)
        self.IDC_dblspinDistance.setProperty("value", 10.0)
        self.IDC_dblspinDistance.setObjectName("IDC_dblspinDistance")
        self.gridLayout_8.addWidget(self.IDC_dblspinDistance, 0, 1, 1, 1)
        self.IDC_rbVertexCount = QtWidgets.QRadioButton(self.IDC_grpVertices)
        self.IDC_rbVertexCount.setObjectName("IDC_rbVertexCount")
        self.gridLayout_8.addWidget(self.IDC_rbVertexCount, 1, 0, 1, 1)
        self.IDC_dblspinVertexCnt = QtWidgets.QDoubleSpinBox(self.IDC_grpVertices)
        self.IDC_dblspinVertexCnt.setDecimals(0)
        self.IDC_dblspinVertexCnt.setMinimum(2.0)
        self.IDC_dblspinVertexCnt.setMaximum(1000000.0)
        self.IDC_dblspinVertexCnt.setProperty("value", 100.0)
        self.IDC_dblspinVertexCnt.setObjectName("IDC_dblspinVertexCnt")
        self.gridLayout_8.addWidget(self.IDC_dblspinVertexCnt, 1, 1, 1, 1)
        self.IDC_chkNodesAndVertices = QtWidgets.QCheckBox(self.IDC_grpVertices)
        self.IDC_chkNodesAndVertices.setChecked(True)
        self.IDC_chkNodesAndVertices.setObjectName("IDC_chkNodesAndVertices")
        self.gridLayout_8.addWidget(self.IDC_chkNodesAndVertices, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.IDC_grpVertices)
        self.IDC_widPolygonLayers = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.IDC_widPolygonLayers.setObjectName("IDC_widPolygonLayers")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.IDC_widPolygonLayers)
        self.gridLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.IDC_grpIntersection = QtWidgets.QGroupBox(self.IDC_widPolygonLayers)
        self.IDC_grpIntersection.setObjectName("IDC_grpIntersection")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.IDC_grpIntersection)
        self.gridLayout_11.setContentsMargins(-1, 3, 9, 0)
        self.gridLayout_11.setVerticalSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.IDC_listPolygons = QtWidgets.QListWidget(self.IDC_grpIntersection)
        self.IDC_listPolygons.setObjectName("IDC_listPolygons")
        self.gridLayout_11.addWidget(self.IDC_listPolygons, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.IDC_grpIntersection, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.IDC_widPolygonLayers)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_10.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.IDC_widNoDataAndProgress = QtWidgets.QWidget(self.IDC_widPolygonLayers)
        self.IDC_widNoDataAndProgress.setObjectName("IDC_widNoDataAndProgress")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.IDC_widNoDataAndProgress)
        self.gridLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.IDC_tbNoDataExport = QtWidgets.QLineEdit(self.IDC_widNoDataAndProgress)
        self.IDC_tbNoDataExport.setInputMask("")
        self.IDC_tbNoDataExport.setObjectName("IDC_tbNoDataExport")
        self.gridLayout_9.addWidget(self.IDC_tbNoDataExport, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.IDC_widNoDataAndProgress)
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem, 0, 2, 1, 1)
        self.IDC_lblCreateStatus = QtWidgets.QLabel(self.IDC_widNoDataAndProgress)
        self.IDC_lblCreateStatus.setObjectName("IDC_lblCreateStatus")
        self.gridLayout_9.addWidget(self.IDC_lblCreateStatus, 0, 3, 1, 1)
        self.gridLayout_10.addWidget(self.IDC_widNoDataAndProgress, 3, 0, 1, 1)
        self.grpCadastre = QtWidgets.QGroupBox(self.IDC_widPolygonLayers)
        self.grpCadastre.setCheckable(True)
        self.grpCadastre.setChecked(False)
        self.grpCadastre.setObjectName("grpCadastre")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.grpCadastre)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cmbCadastreLayer = QtWidgets.QComboBox(self.grpCadastre)
        self.cmbCadastreLayer.setObjectName("cmbCadastreLayer")
        self.verticalLayout_3.addWidget(self.cmbCadastreLayer)
        self.gridLayout_10.addWidget(self.grpCadastre, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.IDC_widPolygonLayers)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.IDC_widVertices = QtWidgets.QWidget(VoGISProfilToolMain)
        self.IDC_widVertices.setObjectName("IDC_widVertices")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.IDC_widVertices)
        self.gridLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_2.addWidget(self.IDC_widVertices)

        self.retranslateUi(VoGISProfilToolMain)
        self.IDC_listRasters.itemChanged['QListWidgetItem*'].connect(VoGISProfilToolMain.lvRasterItemChanged)
        self.buttonBox.rejected.connect(VoGISProfilToolMain.reject)
        self.buttonBox.accepted.connect(VoGISProfilToolMain.accept)
        self.IDC_bSelectVisibleRasters.clicked.connect(VoGISProfilToolMain.selectVisibleRasters)
        self.IDC_bDrawLine.clicked.connect(VoGISProfilToolMain.drawLine)
        self.IDC_dblspinDistance.valueChanged['double'].connect(VoGISProfilToolMain.valueChangedEquiDistance)
        self.IDC_dblspinVertexCnt.valueChanged['double'].connect(VoGISProfilToolMain.valueChangedVertexCount)
        self.IDC_cbLineLayers.currentIndexChanged['int'].connect(VoGISProfilToolMain.lineLayerChanged)
        self.IDC_bRefreshRasterList.clicked.connect(VoGISProfilToolMain.refreshRasterList)
        self.IDC_listPolygons.itemChanged['QListWidgetItem*'].connect(VoGISProfilToolMain.lvPolygonItemChanged)
        QtCore.QMetaObject.connectSlotsByName(VoGISProfilToolMain)

    def retranslateUi(self, VoGISProfilToolMain):
        _translate = QtCore.QCoreApplication.translate
        VoGISProfilToolMain.setWindowTitle(_translate("VoGISProfilToolMain", "VoGIS Profil Tool"))
        self.IDC_grpRaster.setTitle(_translate("VoGISProfilToolMain", "Rastermodell(e) auswählen"))
        self.IDC_bSelectVisibleRasters.setText(_translate("VoGISProfilToolMain", "Im aktuellen Extent sichtbare Raster auswählen"))
        self.IDC_bRefreshRasterList.setText(_translate("VoGISProfilToolMain", "Raster aktualisieren"))
        self.IDC_grpProfilLinien.setTitle(_translate("VoGISProfilToolMain", "Lage der Profillinie(n) festlegen"))
        self.IDC_bDrawLine.setText(_translate("VoGISProfilToolMain", "Profillinie (neu) digitalisieren"))
        self.IDC_chkOnlySelectedFeatures.setText(_translate("VoGISProfilToolMain", "nur selektierte Elemente verwenden"))
        self.IDC_chkLinesExplode.setText(_translate("VoGISProfilToolMain", "Linien explodieren (Multipart Features)"))
        self.IDC_rbShapeLine.setText(_translate("VoGISProfilToolMain", "Profillinie(n) aus Linienthema übernehmen"))
        self.IDC_rbDigi.setText(_translate("VoGISProfilToolMain", "Profillinie am Bildschirm zeichen"))
        self.groupBox.setTitle(_translate("VoGISProfilToolMain", "Linie"))
        self.IDC_tbToY.setText(_translate("VoGISProfilToolMain", "."))
        self.label.setText(_translate("VoGISProfilToolMain", "von:"))
        self.label_2.setText(_translate("VoGISProfilToolMain", "nach:"))
        self.label_3.setText(_translate("VoGISProfilToolMain", "Rechtswert"))
        self.label_4.setText(_translate("VoGISProfilToolMain", "Hochwert"))
        self.IDC_chkLinesMerge.setText(_translate("VoGISProfilToolMain", "Zusammenhängende Linien verbinden"))
        self.IDC_rbStraigthLine.setText(_translate("VoGISProfilToolMain", "gerade Profillinie zwischen zwei Punkten"))
        self.IDC_grpVertices.setTitle(_translate("VoGISProfilToolMain", "Stützstellen festlegen"))
        self.IDC_rbEquiDistance.setText(_translate("VoGISProfilToolMain", "Abstand zwischen den Profilpunkten"))
        self.IDC_rbVertexCount.setText(_translate("VoGISProfilToolMain", "Anzahl Profilpunkte pro Profil"))
        self.IDC_chkNodesAndVertices.setText(_translate("VoGISProfilToolMain", "Profilpunkte erstellen an Knoten und Stützstellen"))
        self.IDC_grpIntersection.setTitle(_translate("VoGISProfilToolMain", "Flächenverschneidung"))
        self.IDC_tbNoDataExport.setText(_translate("VoGISProfilToolMain", "-9999"))
        self.label_5.setText(_translate("VoGISProfilToolMain", "Nodata (Export)"))
        self.IDC_lblCreateStatus.setText(_translate("VoGISProfilToolMain", "0/0"))
        self.grpCadastre.setTitle(_translate("VoGISProfilToolMain", "Kataster Verschneidung"))

